// <auto-generated />
using DesktopService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesktopService.Migrations
{
    [DbContext(typeof(DesktopServiceContext))]
    partial class DesktopServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("foreign_sentence_id_seq");

            modelBuilder.Entity("DesktopService.Entity.ForeignSentence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('foreign_sentence_id_seq')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"), "foreign_sentence_id_seq");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentence");

                    b.Property<string>("TranslatedSentence")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ForeignSentences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
